### ISSUE TITLE
Cannot continue further because of error with connection to Confluence

### ISSUE THREAD

**Issue by monikastevanovska** [WikiTransformationProject/wikitraccs-releases#111]
Can you please help in resolution on this connectivity error:

<img width="839" alt="connection error" src="https://github.com/WikiTransformationProject/wikitraccs-releases/assets/19887628/33488ff4-9150-4045-85cf-eb5fa125d449">

**Comment by heinrich-ulbricht** [comment]
@monikastevanovska WikiTraccs needs two things to show the browser for Confluence login:

1. the Chrome browser
2. the Chrome web driver (for automating Chrome)

The easiest way to get started is to **install the latest Chrome version**. This covers point 1. WikiTraccs looks up the installation path in the registry.

WikiTraccs normally takes care of step 2.

It looks like something failed here. Chrome being found in **Program Files (x86)** instead of **Program Files** also looks off in my eyes.

The log file has all the details about what is going on. Would you please have a look in the **WikiTraccs.GUI/logs** folder? There is one log file per app start.

For me the log file contains this, after having selected the **Test Confluence Connection** button:
![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/3469970/041725dd-9168-4dcb-83a9-1168e429dc0a)
:point_down: 
```
[ 09:22:39 DBG] [https://localhost] Trying to log into Confluence, Config: {"TenantId":"https://localhost","AuthenticationType":"cookie","HumanReadableId":"https://localhost","AuthCookieNames":[""],"PageIdIncludeList":[],"PageIdForLiveUpdate":null,"ReprocessContentWithErrors":false,"SpaceTransfer":{"Enabled":true,"SpaceIncludeList":[],"ForceReprocess":null,"Operations":["retrievecontents"],"$type":"SpaceTransfer"},"PermissionTransfer":{"Enabled":false,"SpaceIncludeList":[],"ForceReprocess":null,"$type":"PermissionTransfer"},"BaseUrl":"https://localhost/","AuthUrl":"","$type":"SourceTenantConfiguration"} | WikiTraccs.Shared.Automation.ConfluenceSessionIdRetriever
[ 09:22:39 DBG] Trying to determine Chrome version to get the right driver for | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 09:22:39 DBG] Reading Chrome binary path from registry path 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe' | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 09:22:39 DBG] Chrome binary path 'C:\Program Files\Google\Chrome\Application\chrome.exe' found in registry and verified | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 09:22:39 DBG] Chrome version: 122.0.6261.57 | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 09:22:39 DBG] Got Chrome major version 122 from chrome version number 122.0.6261 | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 09:22:39 DBG] Determining web driver version from 3-number Chrome version '122.0.6261' from URL https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build-with-downloads.json... | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 09:22:39 DBG] Got web driver version: 122.0.6261.57 | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 09:22:39 DBG] Target directory for web driver: C:\Users\heu\Documents\00_Portable | WikiTraccs.Shared.Misc.ChromeDriverInstaller
```

I'd like to check how this looks on your machine. Could you send this log file to support @ wikitransformationproject.com? But you can also look yourself.

What I'd like to know is how the `Chrome binary path` and `Chrome version` look, and if there are any errors relating to the Chrome driver download in there.

Thanks!

**Comment by monikastevanovska** [comment]
Hello Heinrich,

Thank you very much for the feedback, much appreciated!
I want to inform you that this morning I managed to get successful connection following the procedure described [here](https://www.wikitransformationproject.com/docs/troubleshooting/authentication-issues/confluence/), but please see the message below:
<img width="846" alt="image" src="https://github.com/WikiTransformationProject/wikitraccs-releases/assets/19887628/34bdbe4f-2e78-41b0-9b90-c1998f5d4ad1">

After I close the window I get successful connection
<img width="588" alt="image" src="https://github.com/WikiTransformationProject/wikitraccs-releases/assets/19887628/6515cec6-7da5-4831-8d3e-be4cc7343d91">

but the issue is when I run "Update space inventory and WikiTraccs site, I get the below error and I am not able to continue further:
<img width="647" alt="image" src="https://github.com/WikiTransformationProject/wikitraccs-releases/assets/19887628/e29db3a4-a8bb-4d4c-960d-cd3123ddc874">

**Comment by heinrich-ulbricht** [comment]
@monikastevanovska Glad you found the workaround.

This time I need the log, because usually that contains all information to pinpoint the issue (support @ wikitransformationproject.com). Does Confluence use a single sign on solution or Kerberos to authenticate the user?

**Comment by monikastevanovska** [comment]
Please note that in my last attempt I used: https://wiki.unece.org in the confluence base URL, which is an open confluence space and does not require authentication.
Can you please confirm if the email address where the log should be send contains empty space after "support "?
Is it:   support @wikitransfotmationproject.com or support@wikitransformationproject.com

**Comment by heinrich-ulbricht** [comment]
@monikastevanovska Thank you so much, also for figuring out the spaces in the email address have to go (I should make that explicit).

The issue here is an oversight on my part with regard to the documentation! When using the **cookies.txt** workaround for Chrome issues in combination with **anonymous** authentication - the **AjsRemoteUserKey** value has to be exactly **00000000000000000000000000000001**. I'll add that to the docs.

I could reproduce the issue you have and setting the **AjsRemoteUserKey** in appsettings.json to above value solved it and spaces could be retrieved.

**Comment by monikastevanovska** [comment]
Hello Heinrich,

Thanks a lot for the support! I want to inform you that I successfully managed to connect and perform a migration.

**Comment by heinrich-ulbricht** [comment]
@monikastevanovska Thanks for the feedback, I'm glad to hear that!

Just as heads-up: authenticating with personal access tokens is coming soon, so for authenticated access with Confluence > 7.9 the whole Chrome/cookie thing won't be mandatory anymore.
