### ISSUE TITLE
Copy/Paste not working into GUI for version 1.9

### ISSUE THREAD

**Issue by Troid2k** [WikiTransformationProject/wikitraccs-releases#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Copy text from notepad into the WikiTraccs GUI v1.9 doesn't seem to work. I see it now has a dropdown for copy paste tasks within the GUI, but I cant seem to copy text into the fields. This is also the same for the Settings>Configure Transformation>Transformation when trying to ignore macros.

### Expected Behavior

Used to be able to copy text into the WikiTraccs GUI fields. Now have to type in the detail, or update the config files to work around it.

### WikiTraccs Version

v1.9

### Confluence Version

Confluence 7 (7.18 or newer)

### Confluence Data Center?

- [ ] This is about Confluence Data Center

**Comment by heinrich-ulbricht** [comment]
Hi @Troid2k - it works on my machine (tm).

Could you please try two things:
- right-click the textarea and choose **Paste** from the context menu
- id it doesn't paste: restart the application and try again

The default paste shortcut unfortunately is Ctrl+Y, just wanting to make sure this is not the issue here. And sometimes the console UI seems to forget it can handle pasted text - restarting it so far always helped.

If nothing works, the Windows-way so far always worked:

![paste-via-windows](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/3469970/b0200d7f-f0c8-4ab5-ba48-5b756972bdaf)

If that is the only way for you I'd like to know which version of Windows you are using, and from which context you start WikiTraccs (Windows Explorer, PowerShell, fancy new Windows Terminal, cmd). I saw that making a difference.

**Comment by Troid2k** [comment]
A restart using File > Quit (Ctrl+Q) in the WikiTraccs GUI fixed it. A close using the top right X didn't work, Thanks
